"""empty message

Revision ID: 24ee78998295
Revises: ab344fe33ce8
Create Date: 2025-01-14 01:21:12.885639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '24ee78998295'
down_revision: Union[str, None] = 'ab344fe33ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeroDispositivos', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oficinas', schema=None) as batch_op:
        batch_op.drop_column('numeroDispositivos')

    # ### end Alembic commands ###
